### ISSUE TITLE
Also applies to Netherlands?

### ISSUE THREAD

**Issue by jchristopher** [easydigitaldownloads/edd-remove-german-subscriptions#1]
Just got a report from a customer indicating similar issues from the Netherlands.

**Comment by pippinsplugins** [comment]
I've not seen this before but it very well could be.

**Comment by brianhogg** [comment]
According to PayPal it's just Germany: "German accounts are disabled from Recurring payments due to their funding sources. We do not have any formal documentation but from past experience this is the only country that is currently wired off."

**Comment by jchristopher** [comment]
Good to know, thanks for following up!

**Comment by ciorici** [comment]
Anyone knows if this problem is still actual for Germany?

Not sure if this help, but I've found something that may help others with customers from Germany.

I found under my PayPal account in My Profile > My selling tools > Website preferences an option at the very end:

![screen shot 2018-09-12 at 11 54 54](https://user-images.githubusercontent.com/1674706/45417545-b2688c80-b682-11e8-970a-c05e84d67699.png)

Once I enabled this option, customers from Germany can pay and create subscriptions using their bank account directly:

<img width="764" alt="screen shot 2018-09-10 at 20 28 11" src="https://user-images.githubusercontent.com/1674706/45417636-ea6fcf80-b682-11e8-9824-f5a56a5fc9ab.png">

I guess this is also the preferred way in Germany to pay online.
